--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.article (
    id integer NOT NULL,
    bet_price numeric(38,2),
    blue_label_price numeric(38,2),
    button_open_price numeric(38,2),
    chip_price numeric(38,2),
    cleaning_price numeric(38,2),
    cutting_price numeric(38,2),
    height numeric(38,2),
    label_price numeric(38,2),
    make_pack_price numeric(38,2),
    name character varying(255),
    pack_price numeric(38,2),
    plank_price numeric(38,2),
    side_num numeric(38,2),
    width numeric(38,2),
    yarn_open_price numeric(38,2),
    yarn_price numeric(38,2),
    yellow_chip_price numeric(38,2)
);


ALTER TABLE public.article OWNER TO postgres;

--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: box; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.box (
    id integer NOT NULL,
    box_content_count numeric(38,2),
    box_count numeric(38,2),
    created_at date,
    order_num numeric(38,2),
    article_id integer,
    worker_id integer
);


ALTER TABLE public.box OWNER TO postgres;

--
-- Name: box_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.box ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.box_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cutting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cutting (
    id integer NOT NULL,
    created_at date,
    order_num numeric(38,2),
    ready_prod_count numeric(38,2),
    side_option character varying(255),
    article_id integer,
    worker_id integer,
    CONSTRAINT cutting_side_option_check CHECK (((side_option)::text = ANY ((ARRAY['WIDTH'::character varying, 'HEIGHT'::character varying])::text[])))
);


ALTER TABLE public.cutting OWNER TO postgres;

--
-- Name: cutting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cutting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cutting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expense_company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expense_company (
    id integer NOT NULL,
    amount numeric(38,2),
    created_at date,
    description character varying(255),
    name character varying(255),
    price numeric(38,2),
    type character varying(255)
);


ALTER TABLE public.expense_company OWNER TO postgres;

--
-- Name: expense_company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expense_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expense_tool; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expense_tool (
    id integer NOT NULL,
    amount numeric(38,2),
    created_at date,
    description character varying(255),
    price numeric(38,2),
    expense_type_id integer,
    tool_id integer,
    tool_type_id integer
);


ALTER TABLE public.expense_tool OWNER TO postgres;

--
-- Name: expense_tool_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expense_tool ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_tool_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expense_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expense_type (
    id integer NOT NULL,
    amount numeric(38,2),
    created_at date,
    name character varying(255)
);


ALTER TABLE public.expense_type OWNER TO postgres;

--
-- Name: expense_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expense_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: income_tool; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.income_tool (
    id integer NOT NULL,
    amount numeric(38,2),
    created_at date,
    payment_type character varying(255),
    price numeric(38,2),
    tool_id integer,
    tool_type_id integer,
    CONSTRAINT income_tool_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['CASH'::character varying, 'PERECH'::character varying])::text[])))
);


ALTER TABLE public.income_tool OWNER TO postgres;

--
-- Name: income_tool_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.income_tool ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.income_tool_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_pie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report_pie (
    id integer NOT NULL,
    created_at date,
    date_num_choy integer,
    date_num_sal integer,
    date_num_sumka integer,
    month_date_num integer,
    choy_am numeric(38,2),
    sal_am numeric(38,2),
    sumka_am numeric(38,2)
);


ALTER TABLE public.report_pie OWNER TO postgres;

--
-- Name: report_pie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.report_pie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_pie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sewing; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sewing (
    id integer NOT NULL,
    art_mat numeric(38,2),
    blue_label numeric(38,2),
    button_open_count numeric(38,2),
    chip_count numeric(38,2),
    cleaning_count numeric(38,2),
    count numeric(38,2),
    created_at date,
    order_num numeric(38,2),
    pack_bag numeric(38,2),
    plank_drawing numeric(38,2),
    yarn_open_count numeric(38,2),
    yellow_chip numeric(38,2),
    article_id integer,
    worker_id integer
);


ALTER TABLE public.sewing OWNER TO postgres;

--
-- Name: sewing_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sewing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sewing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tool; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tool (
    id integer NOT NULL,
    code integer,
    color character varying(255),
    dimension character varying(255),
    marka character varying(255),
    name character varying(255),
    size character varying(255)
);


ALTER TABLE public.tool OWNER TO postgres;

--
-- Name: tool_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tool ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tool_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tool_tool_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tool_tool_types (
    tool_id integer NOT NULL,
    tool_types_id integer NOT NULL
);


ALTER TABLE public.tool_tool_types OWNER TO postgres;

--
-- Name: tool_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tool_type (
    id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.tool_type OWNER TO postgres;

--
-- Name: tool_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tool_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tool_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: worker; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.worker (
    id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    role character varying(255)
);


ALTER TABLE public.worker OWNER TO postgres;

--
-- Name: worker_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.worker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.worker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: article; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.article (id, bet_price, blue_label_price, button_open_price, chip_price, cleaning_price, cutting_price, height, label_price, make_pack_price, name, pack_price, plank_price, side_num, width, yarn_open_price, yarn_price, yellow_chip_price) FROM stdin;
1	140.00	100.00	40.00	30.00	30.00	36.00	0.50	0.00	85.00	50/50х4	250.00	20.00	4.00	0.50	400.00	400.00	100.00
\.


--
-- Data for Name: box; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.box (id, box_content_count, box_count, created_at, order_num, article_id, worker_id) FROM stdin;
1	10.00	1.00	2024-08-31	10056136.00	1	1
\.


--
-- Data for Name: cutting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cutting (id, created_at, order_num, ready_prod_count, side_option, article_id, worker_id) FROM stdin;
\.


--
-- Data for Name: expense_company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expense_company (id, amount, created_at, description, name, price, type) FROM stdin;
\.


--
-- Data for Name: expense_tool; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expense_tool (id, amount, created_at, description, price, expense_type_id, tool_id, tool_type_id) FROM stdin;
5	10.00	2024-08-29	\N	100.00	1	6	5
6	5.00	2024-08-29	\N	100.00	3	6	1
4	10.00	2024-08-29	\N	100.00	2	3	4
8	50.00	2024-08-29	\N	100.00	\N	13	21
7	10.00	2024-08-31	\N	7700.00	3	3	4
9	1.00	2024-08-31	\N	10000.00	\N	12	20
10	100.00	2024-07-24	\N	1.00	\N	12	20
11	200.00	2024-07-09		1.00	\N	13	21
\.


--
-- Data for Name: expense_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expense_type (id, amount, created_at, name) FROM stdin;
3	53800.00	2024-08-27	Sumka
2	18000.00	2024-08-27	Choyshab
1	362400.00	2024-08-31	Salfetka
\.


--
-- Data for Name: income_tool; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.income_tool (id, amount, created_at, payment_type, price, tool_id, tool_type_id) FROM stdin;
2	211.00	2024-08-15	CASH	7700.00	3	4
7	49.10	2024-08-01	CASH	33000.00	6	5
6	101.70	2024-08-01	CASH	33000.00	6	1
4	53.00	2024-08-01	CASH	7700.00	3	2
9	236.50	2024-08-29	CASH	33000.00	6	27
5	54.00	2024-08-01	CASH	7700.00	3	26
1	40.00	2024-08-01	CASH	7700.00	3	3
8	440.40	2024-08-23	CASH	33000.00	6	27
3	600.00	2024-08-14	CASH	7700.00	3	4
\.


--
-- Data for Name: report_pie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report_pie (id, created_at, date_num_choy, date_num_sal, date_num_sumka, month_date_num, choy_am, sal_am, sumka_am) FROM stdin;
3	2023-04-21	9	10	11	31	\N	\N	\N
4	2024-08-14	11	10	11	31	\N	\N	\N
\.


--
-- Data for Name: sewing; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sewing (id, art_mat, blue_label, button_open_count, chip_count, cleaning_count, count, created_at, order_num, pack_bag, plank_drawing, yarn_open_count, yellow_chip, article_id, worker_id) FROM stdin;
1	12.00	12.00	12.00	12.00	100.00	100.00	2024-08-31	10056136.00	12.00	12.00	12.00	12.00	1	1
\.


--
-- Data for Name: tool; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tool (id, code, color, dimension, marka, name, size) FROM stdin;
3	10	10	10	10	ТИКИШ ИПИ	10
6	12	12	12	12	ЦЕЛОФАН ПАКЕТ	12
5	12	12	12	12	КОРОБКА	12
9	12	12	12	12	ЭҲТИЁТ ҚИСМЛАР	12
10	12	12	12	12	ЭТИКЕТКА	12
11	12	12	12	12	ТРАНСПОРТ-ИШЧИЛАР	12
12	12	12	12	12	Ovqatlanish	12
13	12	12	12	12	ЭЛЕКТР-ЭНЕРГИЯ	12
14	12	12	12	12	ТАБИИЙ-ГАЗ	12
15	12	12	12	12	АМОРТИЗАЦИЯ-КРЕДИТ	12
16	12	12	12	12	БОШҚАЛАР	12
17	12	12	12	12	Скотч катта	12
18	12	12	12	12	Скотч кичик	12
\.


--
-- Data for Name: tool_tool_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tool_tool_types (tool_id, tool_types_id) FROM stdin;
9	12
9	13
10	14
10	15
5	6
5	7
5	17
5	18
11	19
12	20
13	21
14	22
15	23
16	24
17	8
18	9
3	4
3	3
3	2
3	26
6	5
6	1
6	27
\.


--
-- Data for Name: tool_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tool_type (id, name) FROM stdin;
4	Oq rang
3	Bo'z rang
2	Qora rang
5	55х60cm
1	42х60cm\t
6	46х39х30 (38х42х9см)\t\t
7	49х46х14 (1243)см\t\t
8	Скотч катта (дона)
9	Скотч кичик (дона)
12	МОЙ\t\t
13	ИГНА\t\t
14	GREEN BAG (1372)\t\t
15	OEKO-TEX (5020)\t\t
16	qora rang
17	46(W)х39(L)х30(H) (ёзувсиз)
18	49х46х28 Kitten \t\t
19	ТРАНСПОРТ-ИШЧИЛАР
20	Ovqatlanish
21	ЭЛЕКТР-ЭНЕРГИЯ
22	ТАБИИЙ-ГАЗ
23	АМОРТИЗАЦИЯ-КРЕДИТ
24	БОШҚАЛАР
26	Ko'k rang
27	44x66
\.


--
-- Data for Name: worker; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.worker (id, first_name, last_name, role) FROM stdin;
1	Akmal	Khakimov	Tikuvchi
\.


--
-- Name: article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.article_id_seq', 1, true);


--
-- Name: box_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.box_id_seq', 1, true);


--
-- Name: cutting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cutting_id_seq', 1, false);


--
-- Name: expense_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expense_company_id_seq', 1, false);


--
-- Name: expense_tool_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expense_tool_id_seq', 11, true);


--
-- Name: expense_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expense_type_id_seq', 34, true);


--
-- Name: income_tool_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.income_tool_id_seq', 37, true);


--
-- Name: report_pie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_pie_id_seq', 4, true);


--
-- Name: sewing_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sewing_id_seq', 1, true);


--
-- Name: tool_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tool_id_seq', 1, false);


--
-- Name: tool_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tool_type_id_seq', 33, true);


--
-- Name: worker_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.worker_id_seq', 1, true);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- Name: box box_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.box
    ADD CONSTRAINT box_pkey PRIMARY KEY (id);


--
-- Name: cutting cutting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cutting
    ADD CONSTRAINT cutting_pkey PRIMARY KEY (id);


--
-- Name: expense_company expense_company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expense_company
    ADD CONSTRAINT expense_company_pkey PRIMARY KEY (id);


--
-- Name: expense_tool expense_tool_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expense_tool
    ADD CONSTRAINT expense_tool_pkey PRIMARY KEY (id);


--
-- Name: expense_type expense_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expense_type
    ADD CONSTRAINT expense_type_pkey PRIMARY KEY (id);


--
-- Name: income_tool income_tool_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.income_tool
    ADD CONSTRAINT income_tool_pkey PRIMARY KEY (id);


--
-- Name: report_pie report_pie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_pie
    ADD CONSTRAINT report_pie_pkey PRIMARY KEY (id);


--
-- Name: sewing sewing_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sewing
    ADD CONSTRAINT sewing_pkey PRIMARY KEY (id);


--
-- Name: tool tool_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tool
    ADD CONSTRAINT tool_pkey PRIMARY KEY (id);


--
-- Name: tool_type tool_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tool_type
    ADD CONSTRAINT tool_type_pkey PRIMARY KEY (id);


--
-- Name: worker worker_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.worker
    ADD CONSTRAINT worker_pkey PRIMARY KEY (id);


--
-- Name: income_tool fk2yttigfkt6hyen3i85b012104; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.income_tool
    ADD CONSTRAINT fk2yttigfkt6hyen3i85b012104 FOREIGN KEY (tool_type_id) REFERENCES public.tool_type(id);


--
-- Name: cutting fk3cd1qc2st1xntg91gqoqqy9e4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cutting
    ADD CONSTRAINT fk3cd1qc2st1xntg91gqoqqy9e4 FOREIGN KEY (worker_id) REFERENCES public.worker(id);


--
-- Name: sewing fk5joqm4xbxpnxlr3362r4hd8mq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sewing
    ADD CONSTRAINT fk5joqm4xbxpnxlr3362r4hd8mq FOREIGN KEY (worker_id) REFERENCES public.worker(id);


--
-- Name: income_tool fk5x4c3f4o9iyiqm6r2mwlw32c1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.income_tool
    ADD CONSTRAINT fk5x4c3f4o9iyiqm6r2mwlw32c1 FOREIGN KEY (tool_id) REFERENCES public.tool(id);


--
-- Name: expense_tool fk6qwix8ktro02petnn5m7132n1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expense_tool
    ADD CONSTRAINT fk6qwix8ktro02petnn5m7132n1 FOREIGN KEY (tool_type_id) REFERENCES public.tool_type(id);


--
-- Name: cutting fk9suf8tq3cr7sqnwr8rrf67tuj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cutting
    ADD CONSTRAINT fk9suf8tq3cr7sqnwr8rrf67tuj FOREIGN KEY (article_id) REFERENCES public.article(id);


--
-- Name: box fkc3k7j6xfovnqljjgclqnvyfw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.box
    ADD CONSTRAINT fkc3k7j6xfovnqljjgclqnvyfw FOREIGN KEY (worker_id) REFERENCES public.worker(id);


--
-- Name: expense_tool fke4vp56fjxjibe1hsgc2vur3r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expense_tool
    ADD CONSTRAINT fke4vp56fjxjibe1hsgc2vur3r FOREIGN KEY (tool_id) REFERENCES public.tool(id);


--
-- Name: expense_tool fke9w55ymrw7y9j4pngdiie2ay; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expense_tool
    ADD CONSTRAINT fke9w55ymrw7y9j4pngdiie2ay FOREIGN KEY (expense_type_id) REFERENCES public.expense_type(id);


--
-- Name: sewing fkf6itqh83ut4ndmcst8sch9wyr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sewing
    ADD CONSTRAINT fkf6itqh83ut4ndmcst8sch9wyr FOREIGN KEY (article_id) REFERENCES public.article(id);


--
-- Name: tool_tool_types fkk266fwqsanqjg3n9keltvn3r4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tool_tool_types
    ADD CONSTRAINT fkk266fwqsanqjg3n9keltvn3r4 FOREIGN KEY (tool_types_id) REFERENCES public.tool_type(id);


--
-- Name: tool_tool_types fkk2tfm8b60759sa0tj0f5rbabn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tool_tool_types
    ADD CONSTRAINT fkk2tfm8b60759sa0tj0f5rbabn FOREIGN KEY (tool_id) REFERENCES public.tool(id);


--
-- Name: box fkn0ilkndlmmjl1nqihlb9glwju; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.box
    ADD CONSTRAINT fkn0ilkndlmmjl1nqihlb9glwju FOREIGN KEY (article_id) REFERENCES public.article(id);


--
-- PostgreSQL database dump complete
--

